In [ ]:
import pandas as pd

# Chapter 2: Basics

## Magic Commands
* Start with %
* Designed to facilitate common tasks & help to control behaviour of python
* e.g how long does it take to run code? Data visualization
* The latter is especiall importand (matplotlib integration)
* Use %matplotlib inline to have plots appear in the notebook / have them not interfering with the console session


In [ ]:
%matplotlib inline

## Control Flow

### If-else

In [6]:
x= 3
#if x < 0:
#    print("It's negative")
    
    
if x < 0:
    print("It's negative")
elif x == 0:
    print("Equal to zero")
elif 0 < x < 5:
    print("Positive but smaller than 5")
else:
    print("Positive and larger than or equal to 5")    

Positive but smaller than 5


### For Loops
* To next iteration with: "continue"
* Exit loop with "break"

In [7]:
#for value in collection:
## do something with value

for i in range(4):
    for j in range(4):
        if j > i:
            break
        print((i, j))

(0, 0)
(1, 0)
(1, 1)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


# Chapter 3: Build in Structures & Functions

## Tuple: Fixed length, immutable sequence
* it is NOT possible to modify which objects is created where once the tuple is created
* if the tuple includes a list, this can then be modified
* The list function is frequently used in data processing as a way to materialize an iterator
* Add and remove elements with "append" ,  "pop" (remove by location) & "remove" (Removes first found element given the remove input )
* Use "+" operator to concat list or  "extend" to add multiple elements at once. Using "extend" is typially preferable in terms of speed

In [8]:
tup = 4, 5, 6
nested_tup = (1,3),(7,0,10),5
nested_tup

((1, 3), (7, 0, 10), 5)

In [9]:
# Access elements with square brackets
nested_tup[0]


(1, 3)

In [ ]:
# Convert to tuple with command 
tup = tuple('hello')

In [ ]:
# Concat with +
(4, None, 'foo') + (6, 0) + ('bar',)


In [10]:
#Unpacking
tup = (4, 5, 6)
a, b, c = tup
c

6

## Lists
* Their content can be modified
* Define using square brackets []
* Use extend/append to add elements - and remove to delete
* Pair elements with "zip"


### Basics

a_list = [3,6,8,None,'a']
a_list[0] = 'Not 3'
a_list

In [14]:
# Used as an iterator
gen = range(10)
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
# Adding and removing elements: insert & pop

a_list.append(4)
a_list.insert(1,'New Position 1')
a_list

['Not 3', 'New Position 1', 6, 8, None, 'a', 4, 4]

In [18]:
#Ands its gone
a_list.pop(1)
a_list

['Not 3', 6, 8, None, 'a', 4, 4]

In [19]:
a_list.remove(4)
a_list

['Not 3', 6, 8, None, 'a', 4]

### Concat, combine, sort & search

In [20]:
b_list = [4, None, 'foo'] + [7, 8, (2, 3)]
b_list

[4, None, 'foo', 7, 8, (2, 3)]

In [ ]:
# To a defined list, we can use "extend" to add more elements
x = [4, None, 'foo']
x.extend([7, 8, (2, 3)])
x

In [22]:
# Simple sort
a = [7, 2, 5, 1, 3]
a.sort()
a

[1, 2, 3, 5, 7]

In [24]:
# Sort by len
b = ['saw', 'small', 'He', 'foxes', 'six']
b.sort(key = len)
b

['He', 'saw', 'six', 'small', 'foxes']

In [25]:
# implements binary search and insertion into a sorted list
import bisect

c = [1, 2, 2, 2, 3, 4, 7]
bisect.bisect(c, 5)
c

[1, 2, 2, 2, 3, 4, 7]

In [27]:
#Sliceing - simple

seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[1:5]

[2, 3, 7, 5]

In [28]:
seq[:4]

[7, 2, 3, 7]

In [29]:
seq[2:]

[3, 7, 5, 6, 0, 1]

In [30]:
# Relative to the end
seq[-6:-2]

[3, 7, 5, 6]

In [ ]:
# Zip pairs up elements of lists/tuples
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
zipped = zip(seq1, seq2)
list(zipped)

## Dictionaries (hash mapps/assortative arrays)
* It is a flexibly sized collection of key-value pairs, where key and value are Python objects
* usually created with curley braces {} & colns to separate keys & values
* Delete entries with pop or del keyword
* Obtain the keys with list commands
* Merge them with "update"
* Use enumerate to keep track of indices

In [37]:
#Basics
empty_dict = {}
d1 = {'a' : 'some value', 'b' : [1, 2, 3, 4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [33]:
# Insert & access elements
d1[7] = 'an integer'
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [34]:
d1['b']

[1, 2, 3, 4]

In [ ]:
#You can check if a dict contains a key using the same syntax used for checking
#whether a list or tuple contains a value:

'b' in d1

In [40]:
#Delete values with del keyword or pop method
d1[5] = 'some value'
d1['dummy'] = 'another value'


In [41]:
del d1[5]
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 'dummy': 'another value'}

In [42]:
# Obtain keys
list(d1.keys())

['a', 'b', 'dummy']

In [43]:
d1.update({'b' : 'foo', 'c' : 12})
d1

{'a': 'some value', 'b': 'foo', 'dummy': 'another value', 'c': 12}

In [ ]:
#Enumerate: It’s common when iterating over a sequence to want to keep track of the index of the current item.

# Instead of
#i = 0
    #for value in collection:
    # do something with value
    #i += 1
    
# Use
# for i, value in enumerate(collection):
# do something with value


In [47]:
some_list = ['foo', 'bar', 'baz']
mapping = {}
for i, v in enumerate(some_list):
    mapping[v] = i
    

In [48]:
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

## List comprehension
* They allow you to concisely form a new list by filtering the elements of a collection, transforming the elements passing the filter in one concise expression. 
* They take the basic form: [expr for val in collection if condition]


In [ ]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']
[x.upper() for x in strings if len(x) > 2]

In [ ]:
# Set and dict comprehensions are a natural extension, producing sets and dicts in an
# idiomatically similar way instead of lists.
# dict_comp = {key-expr : value-expr for value in collection if condition}

## Functions
* Use def keyword
* Global vs. local namespace:Assigned within a function -> local i.r. after the function run, the local namespace is destroyed
* Use "local" variables
* Anonymous/Lambda functions -> writing functions consisting of a single statement,  the result is a return value 

In [49]:
def my_function(x, y, z=1.5):
    if z > 1:
        return z * (x + y)
    else:
        return z / (x + y)

In [50]:
my_function(5, 6, z=0.7)

0.06363636363636363

In [51]:
# Functions can return multiple arguments
def f():
    a = 5
    b = 6
    c = 7
    return a, b, c

a, b, c = f()

In [52]:
b

6

In [ ]:
# Lambda functions

#Instead of 

#def short_function(x):
    #return x * 2

# Use
equiv_anon = lambda x: x * 2

# Chapter 4: Numpy
* Performs comple calculations without need for loops
* One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python
* Other Notes: https://github.com/AdityaGogoi/Notes-on-Python-for-Data-Analysis-2nd-Edition/blob/master/1.%20NumPy%20Basics%20-%20Arrays%20and%20Vectorized%20operations.ipynb


In [53]:
import numpy as np
my_arr = np.arange(1000000) # NumPy array

# Time for NumPy operation
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 68.8 ms


In [54]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [55]:
data = np.random.randn(2, 3)
data

array([[-1.83689359,  1.16762718,  0.18947012],
       [ 0.5146962 ,  1.75327085, -0.28466231]])

In [56]:
data * 10
# data + data

array([[-18.36893588,  11.67627178,   1.89470123],
       [  5.14696196,  17.53270849,  -2.84662307]])

### Different ways to create ndarray

1. array - Will create an array out of a list. For list of lists, will create a higher-dimensional array.
2. empty - Creates array without initializing values. May return uninitialized garbage values.
3. zeros - Creates array initialized with zeroes.
4. arange - Create array initialized with range of values.
5. For empty and zeros, pass the size of the array. For creating multi-dimensional arrays, use tuples.


In [58]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [59]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
#Dim?
arr2.ndim

2

In [61]:
#Shape?
arr2.shape

(2, 4)

In [62]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [64]:
np.empty((2, 3, 2))

array([[[1.11306873e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.16709769e-312, 1.86317230e+160]],

       [[1.39641237e-075, 1.90187367e+185],
        [8.37405146e+169, 7.40239924e-038],
        [1.78701736e-051, 1.83256109e-076]]])

In [65]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays
* The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data
* You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method

In [66]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [67]:
arr1.dtype

dtype('float64')

In [68]:
# Convert Types

arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [69]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
loat_arr.dtype

### Arithmetic with NumPy Arrays
* Arrays are important because they enable you to express batch operations on data
* This is called vectorization
* Comparisons between equal sized arrays yields boolean arrays

In [70]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [71]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [72]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# With Scalar [apply to each element of array]
arr ** 0.5

In [73]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing: 1D
* For 1D array easy
* If a scalar is applied to a slice, the value is propagated (Broadcasting)


In [74]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[5]

5

In [76]:
arr[5:8]

array([5, 6, 7])

In [77]:
# Broadcasting
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### Basic Indexing and Slicing: Multi D
* In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays
* Individual elements can be accessed recursively
* In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions
* Comparisons with Numpy arrays are also vectorized. so they result in a Boolean array.

In [78]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [79]:
arr2d[0][2]

3

In [81]:
arr2d[2][2]

9

In [82]:
# Slicing - 1D

arr
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [87]:
# Slicing - 2D
arr2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr2d[1,:3]

array([4, 5, 6])

In [86]:
arr2d[:3,2]

array([3, 6, 9])

In [91]:
# Boolean indexing
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [92]:
names[names != 'Bob']

array(['Joe', 'Will', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [93]:
data = np.random.randn(7, 4)
data

array([[-0.27027175, -0.0129387 , -1.77372649,  1.29019358],
       [ 0.13541312, -1.25638106,  2.31709025, -0.79077796],
       [ 0.09574952, -1.26926507,  0.56481622, -1.44199219],
       [-0.70276019,  1.49459163, -0.27101625,  0.64383382],
       [ 0.42472533,  2.12868539,  1.85390745, -0.18198342],
       [-0.00578627, -0.61862708,  0.70083172,  0.84739174],
       [-0.87237629,  0.61174827, -0.92470231,  0.30791997]])

In [94]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [95]:
# Select all rows with name "Bob" -> rows 0 and 4 
data[names == 'Bob']

array([[-0.27027175, -0.0129387 , -1.77372649,  1.29019358],
       [-0.70276019,  1.49459163, -0.27101625,  0.64383382]])

In [98]:
# Rows and columns (only start from third col)
data[names == 'Bob', 2:]

array([[-0.27027175, -0.0129387 , -1.77372649,  1.29019358],
       [-0.70276019,  1.49459163, -0.27101625,  0.64383382]])

In [99]:
cond = names == 'Bob'
data[~cond]

array([[ 0.13541312, -1.25638106,  2.31709025, -0.79077796],
       [ 0.09574952, -1.26926507,  0.56481622, -1.44199219],
       [ 0.42472533,  2.12868539,  1.85390745, -0.18198342],
       [-0.00578627, -0.61862708,  0.70083172,  0.84739174],
       [-0.87237629,  0.61174827, -0.92470231,  0.30791997]])

In [100]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [101]:
data[mask]

array([[-0.27027175, -0.0129387 , -1.77372649,  1.29019358],
       [ 0.09574952, -1.26926507,  0.56481622, -1.44199219],
       [-0.70276019,  1.49459163, -0.27101625,  0.64383382],
       [ 0.42472533,  2.12868539,  1.85390745, -0.18198342]])

# Chapter 5: Getting started with pandas